project:
  type: book
filters:
  - pseudocode
book:
  title: The Art of Scientific Computation 
  subtitle: A survey of techniques for simulation of the abelian sandpile model
  author:
     name: James Reuben Bender
     affiliation: The University of Melbourne
     roles: writing
     corresponding: true
  date: today
  chapters:
    - index.qmd
    - chapters/Introduction.qmd
    - chapters/Languages.qmd
    - chapters/Algorithms.qmd
    - chapters/References.qmd
  appendices: 
    - chapters/Appendix_Julia.qmd
bibliography: TASC.bib

format:
  pdf
  # (other formats)
  # pdf: default

execute:
  freeze: true



